"""add_user_activity_logs_and_sessions_tables

Revision ID: 0acce6a01a31
Revises: f3c4d5e6a7b8
Create Date: 2025-10-12 17:05:51.671584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0acce6a01a31'
down_revision: Union[str, None] = 'f3c4d5e6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activity_logs_id'), 'user_activity_logs', ['id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_category', table_name='posts')
    op.drop_index('idx_created_at', table_name='posts')
    op.drop_index('idx_likes_count', table_name='posts')
    op.drop_index('idx_title_content', table_name='posts', mysql_prefix='FULLTEXT')
    op.drop_table('posts')
    op.drop_index('idx_product_inquiries_created_at', table_name='product_inquiries')
    op.drop_index('idx_product_inquiries_product_id', table_name='product_inquiries')
    op.drop_index('idx_product_inquiries_status', table_name='product_inquiries')
    op.drop_table('product_inquiries')
    op.drop_index('idx_post_interaction', table_name='post_interactions')
    op.drop_index('unique_user_post', table_name='post_interactions')
    op.drop_table('post_interactions')
    op.drop_table('portfolio')
    op.drop_index('idx_post_anonymous', table_name='anonymous_interactions')
    op.drop_index('unique_anonymous_interaction', table_name='anonymous_interactions')
    op.drop_table('anonymous_interactions')
    op.drop_index('idx_is_active', table_name='product_categories')
    op.drop_index('idx_name', table_name='product_categories')
    op.drop_index('name', table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index('idx_post_comments', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_post_media', table_name='post_media')
    op.drop_table('post_media')
    op.drop_index('country_code', table_name='global_hotel_mapping')
    op.drop_index('idx_grnconnect', table_name='global_hotel_mapping')
    op.drop_index('idx_hotelbeds', table_name='global_hotel_mapping')
    op.drop_index('idx_lastUpdate', table_name='global_hotel_mapping')
    op.drop_index('idx_status', table_name='global_hotel_mapping')
    op.drop_index('idx_table_status', table_name='global_hotel_mapping')
    op.drop_index('idx_table_status_goglobal', table_name='global_hotel_mapping')
    op.drop_index('idx_tbo', table_name='global_hotel_mapping')
    op.drop_index('idx_vervotechid_status', table_name='global_hotel_mapping')
    op.drop_table('global_hotel_mapping')
    op.drop_index('idx_category', table_name='products')
    op.drop_index('idx_created_at', table_name='products')
    op.drop_index('idx_is_active', table_name='products')
    op.drop_index('idx_name_description', table_name='products', mysql_prefix='FULLTEXT')
    op.drop_index('idx_price', table_name='products')
    op.drop_index('idx_stock', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_product_images', table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('email', table_name='admin_users')
    op.drop_index('idx_email', table_name='admin_users')
    op.drop_index('idx_is_admin', table_name='admin_users')
    op.drop_index('idx_username', table_name='admin_users')
    op.drop_index('username', table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index('idx_post_anonymous_comments', table_name='anonymous_comments')
    op.drop_table('anonymous_comments')
    op.drop_index('idx_hotel_id', table_name='provider_mappings')
    op.drop_index('idx_ittid', table_name='provider_mappings')
    op.drop_index('idx_provider_id', table_name='provider_mappings')
    op.drop_index('idx_provider_name', table_name='provider_mappings')
    op.alter_column('rate_type_info', 'ittid',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_index('rate_type_info_ibfk_1_copy', table_name='rate_type_info')
    op.create_foreign_key(None, 'rate_type_info', 'hotels', ['ittid'], ['ittid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rate_type_info', type_='foreignkey')
    op.create_index('rate_type_info_ibfk_1_copy', 'rate_type_info', ['provider_mapping_id'], unique=False)
    op.alter_column('rate_type_info', 'ittid',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_index('idx_provider_name', 'provider_mappings', ['provider_name'], unique=False)
    op.create_index('idx_provider_id', 'provider_mappings', ['id'], unique=False)
    op.create_index('idx_ittid', 'provider_mappings', ['ittid'], unique=False)
    op.create_index('idx_hotel_id', 'provider_mappings', ['provider_id'], unique=False)
    op.create_table('anonymous_comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_identifier', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='anonymous_comments_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_post_anonymous_comments', 'anonymous_comments', ['post_id', 'created_at'], unique=False)
    op.create_table('admin_users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='User accounts for authentication and authorization',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='User accounts for authentication and authorization',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'admin_users', ['username'], unique=True)
    op.create_index('idx_username', 'admin_users', ['username'], unique=False)
    op.create_index('idx_is_admin', 'admin_users', ['is_admin'], unique=False)
    op.create_index('idx_email', 'admin_users', ['email'], unique=False)
    op.create_index('email', 'admin_users', ['email'], unique=True)
    op.create_table('product_images',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', mysql.TEXT(), nullable=False),
    sa.Column('is_primary', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_images_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_product_images', 'product_images', ['product_id', 'is_primary'], unique=False)
    op.create_table('products',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('stock', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('discount', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('specifications', mysql.TEXT(), nullable=True),
    sa.Column('image_url', mysql.TEXT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], name='products_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Product catalog for e-commerce functionality',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='Product catalog for e-commerce functionality',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_stock', 'products', ['stock'], unique=False)
    op.create_index('idx_price', 'products', ['price'], unique=False)
    op.create_index('idx_name_description', 'products', ['name', 'description'], unique=False, mysql_prefix='FULLTEXT')
    op.create_index('idx_is_active', 'products', ['is_active'], unique=False)
    op.create_index('idx_created_at', 'products', ['created_at'], unique=False)
    op.create_index('idx_category', 'products', ['category'], unique=False)
    op.create_table('global_hotel_mapping',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lastUpdate', mysql.TIMESTAMP(), nullable=True),
    sa.Column('mapStatus', mysql.VARCHAR(length=10), server_default=sa.text("'pending'"), nullable=True, comment='pending/updated'),
    sa.Column('ittid', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('VervotechId', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('GiataCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contentUpdateStatus', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Latitude', mysql.FLOAT(), nullable=True),
    sa.Column('Longitude', mysql.FLOAT(), nullable=True),
    sa.Column('AddressLine1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('AddressLine2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CityName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StateName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StateCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CountryName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CountryCode', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('PostalCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Rating', mysql.FLOAT(), nullable=True),
    sa.Column('PropertyType', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('PrimaryPhoto', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_german2_ci'), nullable=True),
    sa.Column('ChainName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ChainCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('BrandName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CityCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CityLocationId', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('MasterCityName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('LocationIds', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Phones', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Emails', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Fax', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Website', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('hotelbeds', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ratehawkhotel', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_a', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_b', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_c', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_d', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_e', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('adivahahotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('adivahahotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('juniperhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mikihotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('paximumhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('adonishotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('w2mhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('letsflyhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('illusionshotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('roomerang_a', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('roomerang_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang_e', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_vervotechid_status', 'global_hotel_mapping', ['VervotechId', 'mapStatus'], unique=False)
    op.create_index('idx_tbo', 'global_hotel_mapping', ['tbohotel'], unique=False)
    op.create_index('idx_table_status_goglobal', 'global_hotel_mapping', ['goglobal'], unique=False)
    op.create_index('idx_table_status', 'global_hotel_mapping', ['grnconnect', 'goglobal'], unique=False)
    op.create_index('idx_status', 'global_hotel_mapping', ['GiataCode', 'mapStatus'], unique=False)
    op.create_index('idx_lastUpdate', 'global_hotel_mapping', ['lastUpdate'], unique=False)
    op.create_index('idx_hotelbeds', 'global_hotel_mapping', ['hotelbeds'], unique=False)
    op.create_index('idx_grnconnect', 'global_hotel_mapping', ['grnconnect'], unique=False)
    op.create_index('country_code', 'global_hotel_mapping', ['CountryCode'], unique=False)
    op.create_table('post_media',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('media_type', mysql.ENUM('image', 'video'), nullable=False),
    sa.Column('media_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('original_filename', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_media_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_post_media', 'post_media', ['post_id', 'media_order'], unique=False)
    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='comments_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], name='comments_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_post_comments', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'product_categories', ['name'], unique=True)
    op.create_index('idx_name', 'product_categories', ['name'], unique=False)
    op.create_index('idx_is_active', 'product_categories', ['is_active'], unique=False)
    op.create_table('anonymous_interactions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_identifier', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('interaction_type', mysql.ENUM('like', 'dislike'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='anonymous_interactions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_anonymous_interaction', 'anonymous_interactions', ['post_id', 'user_identifier'], unique=True)
    op.create_index('idx_post_anonymous', 'anonymous_interactions', ['post_id', 'interaction_type'], unique=False)
    op.create_table('portfolio',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('technologies', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('project_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('github_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Portfolio items showcasing projects and skills',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='Portfolio items showcasing projects and skills',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('post_interactions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interaction_type', mysql.ENUM('like', 'dislike'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_interactions_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], name='post_interactions_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_user_post', 'post_interactions', ['user_id', 'post_id'], unique=True)
    op.create_index('idx_post_interaction', 'post_interactions', ['post_id', 'interaction_type'], unique=False)
    op.create_table('product_inquiries',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('customer_email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('customer_phone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('inquiry_type', mysql.VARCHAR(length=50), server_default=sa.text("'purchase'"), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('responded_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_inquiries_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Customer inquiries for products',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='Customer inquiries for products',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_product_inquiries_status', 'product_inquiries', ['status'], unique=False)
    op.create_index('idx_product_inquiries_product_id', 'product_inquiries', ['product_id'], unique=False)
    op.create_index('idx_product_inquiries_created_at', 'product_inquiries', ['created_at'], unique=False)
    op.create_table('posts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('category', mysql.ENUM('tech', 'food', 'activity'), nullable=False),
    sa.Column('tags', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('media_urls', mysql.JSON(), nullable=True),
    sa.Column('likes_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('dislikes_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('comments_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Blog posts with categories and media support',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='Blog posts with categories and media support',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_title_content', 'posts', ['title', 'content'], unique=False, mysql_prefix='FULLTEXT')
    op.create_index('idx_likes_count', 'posts', ['likes_count'], unique=False)
    op.create_index('idx_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('idx_category', 'posts', ['category'], unique=False)
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_activity_logs_id'), table_name='user_activity_logs')
    op.drop_table('user_activity_logs')
    # ### end Alembic commands ###
