"""add user provider permission table

Revision ID: 264a357df957
Revises: 355e02bd3bd2
Create Date: 2025-05-18 23:53:51.168390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264a357df957'
down_revision: Union[str, None] = '355e02bd3bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_mappings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('provider_mappings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_mappings', 'updated_at')
    op.drop_column('provider_mappings', 'created_at')
    # ### end Alembic commands ###
