"""Add giver_email and receiver_email to PointTransaction

Revision ID: 2c76518eaf5c
Revises: 6d280c732506
Create Date: 2025-06-01 13:03:07.416562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2c76518eaf5c'
down_revision: Union[str, None] = '6d280c732506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'value',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('idx_hotel_ittid'), table_name='hotels')
    op.drop_index(op.f('idx_ittid'), table_name='provider_mappings')
    op.drop_index(op.f('idx_provider_id'), table_name='provider_mappings')
    op.drop_index(op.f('idx_provider_name'), table_name='provider_mappings')
    op.add_column('rate_type_info', sa.Column('ittid', sa.String(length=100), nullable=False))
    op.drop_index(op.f('rate_type_info_ibfk_1_copy'), table_name='rate_type_info')
    op.create_foreign_key('fk_rate_type_info_ittid', 'rate_type_info', 'hotels', ['ittid'], ['ittid'])
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_rate_type_info_ittid', 'rate_type_info', type_='foreignkey')
    op.create_index(op.f('rate_type_info_ibfk_1_copy'), 'rate_type_info', ['provider_mapping_id'], unique=False)
    op.drop_column('rate_type_info', 'ittid')
    op.create_index(op.f('idx_provider_name'), 'provider_mappings', ['provider_name'], unique=False)
    op.create_index(op.f('idx_provider_id'), 'provider_mappings', ['id'], unique=False)
    op.create_index(op.f('idx_ittid'), 'provider_mappings', ['ittid'], unique=False)
    op.create_index(op.f('idx_hotel_ittid'), 'hotels', ['ittid'], unique=False)
    op.alter_column('contacts', 'value',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
