"""Fix user role enum

Revision ID: 2d831e0f1cdf
Revises: 2431aa5316a6
Create Date: 2025-05-11 20:06:06.907706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2d831e0f1cdf'
down_revision: Union[str, None] = '2431aa5316a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provider_mappings', 'system_type',
               existing_type=mysql.ENUM('a', 'b', 'c', 'd', 'e'),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('SUPER_USER', 'ADMIN_USER', 'GENERAL_USER'),
               type_=sa.Enum('super_user', 'admin_user', 'general_user', name='user_role_enum', native_enum=False),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('super_user', 'admin_user', 'general_user', name='user_role_enum', native_enum=False),
               type_=mysql.ENUM('SUPER_USER', 'ADMIN_USER', 'GENERAL_USER'),
               nullable=True)
    op.alter_column('provider_mappings', 'system_type',
               existing_type=mysql.ENUM('a', 'b', 'c', 'd', 'e'),
               nullable=True)
    # ### end Alembic commands ###
