"""Migrate database schema

Revision ID: 5e6bb6e50c30
Revises: be5292f9309f
Create Date: 2025-05-09 00:30:46.651756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e6bb6e50c30'
down_revision: Union[str, None] = 'be5292f9309f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zz_modules_supplier')
    op.drop_table('new')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('zz_modules_supplier',
    sa.Column('Id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('last_update', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('supplier_type', mysql.VARCHAR(length=30), server_default=sa.text("'HOTEL'"), nullable=True, comment='HOTEL/FLIGHT/TRASNFER'),
    sa.Column('supplier_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('supplier_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('title_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_gds', mysql.VARCHAR(length=3), server_default=sa.text("'NO'"), nullable=True, comment='YES or NO'),
    sa.Column('subscription_type', mysql.VARCHAR(length=100), server_default=sa.text("'FREE'"), nullable=True, comment='FREE/PAID/MONTHLY/YEARLY/ONE-TIME'),
    sa.Column('icon_code', mysql.VARCHAR(length=255), server_default=sa.text("'fas fa-cloud-showers-heavy'"), nullable=True),
    sa.Column('icon_color', mysql.VARCHAR(length=255), server_default=sa.text("'7601eb'"), nullable=True),
    sa.Column('logo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('supplier_desc', mysql.TEXT(), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=255), server_default=sa.text("'15'"), nullable=True),
    sa.Column('currency', mysql.VARCHAR(length=255), server_default=sa.text("'USD'"), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=11), server_default=sa.text("'disable'"), nullable=True, comment='active/disable'),
    sa.Column('base_url', mysql.TEXT(), nullable=True),
    sa.Column('color_class', mysql.VARCHAR(length=50), server_default=sa.text("'purple'"), nullable=True),
    sa.Column('reseller_module', mysql.VARCHAR(length=3), server_default=sa.text("'no'"), nullable=True, comment='no or yes'),
    sa.Column('youtube_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('how_to_youtube_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('api_docs_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('website_url', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
