"""Add giver_email and receiver_email to PointTransaction

Revision ID: aa7cd5e901a2
Revises: 2d09216bbe39
Create Date: 2025-05-31 13:36:29.602027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa7cd5e901a2'
down_revision: Union[str, None] = '2d09216bbe39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ittid'), table_name='provider_mappings')
    op.drop_index(op.f('idx_provider_id'), table_name='provider_mappings')
    op.drop_index(op.f('idx_provider_name'), table_name='provider_mappings')
    op.create_foreign_key(None, 'provider_mappings', 'hotels', ['ittid'], ['ittid'])
    op.drop_column('summary_status', 'total_rooms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summary_status', sa.Column('total_rooms', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'provider_mappings', type_='foreignkey')
    op.create_index(op.f('idx_provider_name'), 'provider_mappings', ['provider_name'], unique=False)
    op.create_index(op.f('idx_provider_id'), 'provider_mappings', ['id'], unique=False)
    op.create_index(op.f('idx_ittid'), 'provider_mappings', ['ittid'], unique=False)
    # ### end Alembic commands ###
