"""Update user_role_enum to match new UserRole values

Revision ID: d7ec56cfb3c8
Revises: 30c9267802bb
Create Date: 2025-05-11 21:28:56.385193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ec56cfb3c8'
down_revision: Union[str, None] = '30c9267802bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo_hotel', sa.Column('rating', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demo_hotel', 'rating')
    # ### end Alembic commands ###
