"""Add demo_hotel table

Revision ID: f85655f8b571
Revises: 419a821ab913
Create Date: 2025-05-09 23:51:11.040204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f85655f8b571'
down_revision: Union[str, None] = '419a821ab913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('damo_table')
    op.drop_table('country_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_info',
    sa.Column('Id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('ittid', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Latitude', mysql.FLOAT(), nullable=True),
    sa.Column('Longitude', mysql.FLOAT(), nullable=True),
    sa.Column('AddressLine1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('AddressLine2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CityName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StateName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StateCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CountryName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CountryCode', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('PostalCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CityCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CityLocationId', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('MasterCityName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('LocationIds', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('akbar_status', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('damo_table',
    sa.Column('Id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('ittid', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Latitude', mysql.FLOAT(), nullable=True),
    sa.Column('Longitude', mysql.FLOAT(), nullable=True),
    sa.Column('AddressLine1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('AddressLine2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CityName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StateName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StateCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CountryName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CountryCode', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('PostalCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CityCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CityLocationId', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('MasterCityName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('LocationIds', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('akbar_status', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
