"""Initial

Revision ID: 89efd5670b0f
Revises: 
Create Date: 2025-05-06 12:56:51.380759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89efd5670b0f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('country_code', table_name='itt_mapping_v01')
    op.drop_index('idx_address', table_name='itt_mapping_v01')
    op.drop_index('idx_cityname', table_name='itt_mapping_v01')
    op.drop_index('idx_contentStatus', table_name='itt_mapping_v01')
    op.drop_index('idx_grnconnect', table_name='itt_mapping_v01')
    op.drop_index('idx_hotelbeds', table_name='itt_mapping_v01')
    op.drop_index('idx_lastUpdate', table_name='itt_mapping_v01')
    op.drop_index('idx_latitude_longitude', table_name='itt_mapping_v01')
    op.drop_index('idx_name', table_name='itt_mapping_v01')
    op.drop_index('idx_status', table_name='itt_mapping_v01')
    op.drop_index('idx_table_status', table_name='itt_mapping_v01')
    op.drop_index('idx_table_status_goglobal', table_name='itt_mapping_v01')
    op.drop_index('idx_tbo', table_name='itt_mapping_v01')
    op.drop_index('idx_vervotechid_status', table_name='itt_mapping_v01')
    op.drop_table('itt_mapping_v01')
    op.drop_table('suppliers')
    op.drop_index('for_vervotech_id', table_name='vervotech_mapping')
    op.drop_index('idx_provider_family_hotel_id', table_name='vervotech_mapping')
    op.drop_index('vervotech_idx', table_name='vervotech_mapping')
    op.drop_table('vervotech_mapping')
    op.drop_index('country_code', table_name='global_hotel_mapping_copy')
    op.drop_index('idx_city_name', table_name='global_hotel_mapping_copy')
    op.drop_index('idx_contentStatus', table_name='global_hotel_mapping_copy')
    op.drop_index('idx_content_update_status', table_name='global_hotel_mapping_copy')
    op.drop_index('idx_country_name', table_name='global_hotel_mapping_copy')
    op.drop_index('idx_grnconnect', table_name='global_hotel_mapping_copy')
    op.drop_index('idx_hotelbeds', table_name='global_hotel_mapping_copy')
    op.drop_index('idx_lastUpdate', table_name='global_hotel_mapping_copy')
    op.drop_index('idx_status', table_name='global_hotel_mapping_copy')
    op.drop_index('idx_table_status', table_name='global_hotel_mapping_copy')
    op.drop_index('idx_table_status_goglobal', table_name='global_hotel_mapping_copy')
    op.drop_index('idx_tbo', table_name='global_hotel_mapping_copy')
    op.drop_index('idx_vervotechid_status', table_name='global_hotel_mapping_copy')
    op.drop_table('global_hotel_mapping_copy')
    op.drop_table('vervotech_update_data_info')
    op.drop_index('idx_address', table_name='mapping_short_info')
    op.drop_index('idx_address_1', table_name='mapping_short_info')
    op.drop_index('idx_cityname', table_name='mapping_short_info')
    op.drop_index('idx_cityname_1', table_name='mapping_short_info')
    op.drop_index('idx_latitude_longitude', table_name='mapping_short_info')
    op.drop_index('idx_latitude_longitude_1', table_name='mapping_short_info')
    op.drop_index('idx_name', table_name='mapping_short_info')
    op.drop_index('idx_name_1', table_name='mapping_short_info')
    op.drop_table('mapping_short_info')
    op.drop_table('oryx_destination_id')
    op.drop_table('hotels_info_with_gidestination_code')
    op.drop_index('idx_city_name', table_name='country_info')
    op.drop_index('idx_content_update_status', table_name='country_info')
    op.drop_index('idx_country_name', table_name='country_info')
    op.drop_table('country_info')
    op.drop_table('gitata_provider_family')
    op.drop_index('username', table_name='users_for_flask')
    op.drop_table('users_for_flask')
    op.drop_index('unique_city', table_name='master_dotw')
    op.drop_table('master_dotw')
    op.drop_table('vervotech_ProviderFamily')
    op.drop_index('idx_index', table_name='vervotech_hotel_map_update')
    op.drop_table('vervotech_hotel_map_update')
    op.drop_table('giata_hotel_mapping')
    op.drop_table('all_country_name')
    op.drop_index('idx_created_at', table_name='vervotech_hotel_map_new')
    op.drop_index('idx_index', table_name='vervotech_hotel_map_new')
    op.drop_table('vervotech_hotel_map_new')
    op.drop_table('hotels_info')
    op.drop_table('users')
    op.drop_index('idx_unicaid_name', table_name='vervotech_mapping_2')
    op.drop_table('vervotech_mapping_2')
    op.drop_table('akbar_location_master')
    op.drop_index('idx_index', table_name='vervotech_hotel_list')
    op.drop_table('vervotech_hotel_list')
    op.drop_table('zz_modules_supplier')
    op.drop_table('hotel_info_all')
    op.drop_table('country_code')
    op.drop_table('backup_vervotech_mapping')
    op.drop_index('idx_hotel_id', table_name='goglobal_master')
    op.drop_table('goglobal_master')
    op.drop_table('hotels')
    op.drop_index('idx_destinationId', table_name='oryx_systemid_master')
    op.drop_index('idx_giDestinationId', table_name='oryx_systemid_master')
    op.drop_table('oryx_systemid_master')
    op.drop_index('unique_id', table_name='innova_hotels_main')
    op.drop_table('innova_hotels_main')
    op.drop_index('country_code', table_name='global_hotel_mapping')
    op.drop_index('idx_address', table_name='global_hotel_mapping')
    op.drop_index('idx_cityname', table_name='global_hotel_mapping')
    op.drop_index('idx_contentStatus', table_name='global_hotel_mapping')
    op.drop_index('idx_grnconnect', table_name='global_hotel_mapping')
    op.drop_index('idx_hotelbeds', table_name='global_hotel_mapping')
    op.drop_index('idx_lastUpdate', table_name='global_hotel_mapping')
    op.drop_index('idx_latitude_longitude', table_name='global_hotel_mapping')
    op.drop_index('idx_name', table_name='global_hotel_mapping')
    op.drop_index('idx_status', table_name='global_hotel_mapping')
    op.drop_index('idx_table_status', table_name='global_hotel_mapping')
    op.drop_index('idx_table_status_goglobal', table_name='global_hotel_mapping')
    op.drop_index('idx_tbo', table_name='global_hotel_mapping')
    op.drop_index('idx_vervotechid_status', table_name='global_hotel_mapping')
    op.drop_table('global_hotel_mapping')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_hotel_mapping',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('lastUpdate', mysql.TIMESTAMP(), nullable=True),
    sa.Column('mapStatus', mysql.VARCHAR(length=10), server_default=sa.text("'pending'"), nullable=True, comment='pending/updated'),
    sa.Column('ittid', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('VervotechId', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('GiataCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contentUpdateStatus', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Latitude', mysql.FLOAT(), nullable=True),
    sa.Column('Longitude', mysql.FLOAT(), nullable=True),
    sa.Column('AddressLine1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('AddressLine2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CityName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StateName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StateCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CountryName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CountryCode', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('PostalCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Rating', mysql.FLOAT(), nullable=True),
    sa.Column('PropertyType', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ChainName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ChainCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('BrandName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CityCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CityLocationId', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('MasterCityName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('LocationIds', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Phones', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Emails', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Fax', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Website', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('hotelbeds', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ratehawkhotel', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_a', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_b', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_c', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_d', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_e', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('adivahahotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('adivahahotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('juniperhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mikihotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('paximumhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('adonishotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('w2mhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('letsflyhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('illusionshotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('roomerang_a', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('roomerang_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang_e', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_vervotechid_status', 'global_hotel_mapping', ['VervotechId', 'mapStatus'], unique=False)
    op.create_index('idx_tbo', 'global_hotel_mapping', ['tbohotel'], unique=False)
    op.create_index('idx_table_status_goglobal', 'global_hotel_mapping', ['goglobal'], unique=False)
    op.create_index('idx_table_status', 'global_hotel_mapping', ['grnconnect', 'goglobal'], unique=False)
    op.create_index('idx_status', 'global_hotel_mapping', ['GiataCode', 'mapStatus'], unique=False)
    op.create_index('idx_name', 'global_hotel_mapping', ['Name'], unique=False)
    op.create_index('idx_latitude_longitude', 'global_hotel_mapping', ['Latitude', 'Longitude'], unique=False)
    op.create_index('idx_lastUpdate', 'global_hotel_mapping', ['lastUpdate'], unique=False)
    op.create_index('idx_hotelbeds', 'global_hotel_mapping', ['hotelbeds'], unique=False)
    op.create_index('idx_grnconnect', 'global_hotel_mapping', ['grnconnect'], unique=False)
    op.create_index('idx_contentStatus', 'global_hotel_mapping', ['contentUpdateStatus'], unique=False)
    op.create_index('idx_cityname', 'global_hotel_mapping', ['CityName'], unique=False)
    op.create_index('idx_address', 'global_hotel_mapping', ['AddressLine1', 'AddressLine2'], unique=False)
    op.create_index('country_code', 'global_hotel_mapping', ['CountryCode'], unique=False)
    op.create_table('innova_hotels_main',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('IttId', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('VervotechId', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('GiataCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('SupplierCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('HotelId', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('DestinationId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('City', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CityCode', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('State', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StateCode', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('PostCode', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Country', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CountryCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('HotelType', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('HotelName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Latitude', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Longitude', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PrimaryPhoto', mysql.TEXT(), nullable=True),
    sa.Column('AddressLine1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('AddressLine2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('HotelReview', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Website', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ContactNumber', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('FaxNumber', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('HotelStar', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Amenities_1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Amenities_2', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Amenities_3', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Amenities_4', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Amenities_5', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('MapStatus', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('JsonContentStatus', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ContentLastUpdateDate', mysql.TIMESTAMP(), nullable=True),
    sa.Column('Confidence', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CreatedAt', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ModifiedOn', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_id', 'innova_hotels_main', ['Id'], unique=True)
    op.create_table('oryx_systemid_master',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('giDestinationId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('destinationId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('systemId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('city', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('imageUrl', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('lat', mysql.FLOAT(), nullable=True),
    sa.Column('lon', mysql.FLOAT(), nullable=True),
    sa.Column('countryName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('countryCode', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mappings', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_giDestinationId', 'oryx_systemid_master', ['giDestinationId'], unique=False)
    op.create_index('idx_destinationId', 'oryx_systemid_master', ['destinationId'], unique=False)
    op.create_table('hotels',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('star_rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('supplier_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('goglobal_master',
    sa.Column('hotelCode', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('hotelName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('latitude', mysql.FLOAT(), nullable=True),
    sa.Column('longitude', mysql.FLOAT(), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('categoryCode', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('giataCode', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_hotel_id', 'goglobal_master', ['hotelCode'], unique=False)
    op.create_table('backup_vervotech_mapping',
    sa.Column('Id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('last_update', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('VervotechId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GiataCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('UpdateDateFormat', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderHotelId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderFamily', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ModifiedOn', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ChannelIds', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderLocationCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hotel_city', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hotel_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hotel_country', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hotel_longitude', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hotel_latitude', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('country_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content_update_status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('country_code',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('hotel_country', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('country_code', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('hotel_info_all',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('GiDestinationId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('HotelName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('SystemId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Rating', mysql.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('City', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Address1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Address2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ZipCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ImageUrl', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('CountryName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CountryCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('StatusUpdate', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('HotelInfo', mysql.JSON(), nullable=True),
    sa.Column('StatusUpdateHotelInfo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CreatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ModifiedOn', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('zz_modules_supplier',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('timestamp', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('last_update', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('supplier_type', mysql.VARCHAR(length=30), server_default=sa.text("'HOTEL'"), nullable=True, comment='HOTEL/FLIGHT/TRASNFER'),
    sa.Column('supplier_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('supplier_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('title_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('is_gds', mysql.VARCHAR(length=3), server_default=sa.text("'NO'"), nullable=True, comment='YES or NO'),
    sa.Column('subscription_type', mysql.VARCHAR(length=100), server_default=sa.text("'FREE'"), nullable=True, comment='FREE/PAID/MONTHLY/YEARLY/ONE-TIME'),
    sa.Column('icon_code', mysql.VARCHAR(length=255), server_default=sa.text("'fas fa-cloud-showers-heavy'"), nullable=True),
    sa.Column('icon_color', mysql.VARCHAR(length=255), server_default=sa.text("'7601eb'"), nullable=True),
    sa.Column('logo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('supplier_desc', mysql.TEXT(), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=255), server_default=sa.text("'15'"), nullable=True),
    sa.Column('currency', mysql.VARCHAR(length=255), server_default=sa.text("'USD'"), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=11), server_default=sa.text("'disable'"), nullable=True, comment='active/disable'),
    sa.Column('base_url', mysql.TEXT(), nullable=True),
    sa.Column('color_class', mysql.VARCHAR(length=50), server_default=sa.text("'purple'"), nullable=True),
    sa.Column('reseller_module', mysql.VARCHAR(length=3), server_default=sa.text("'no'"), nullable=True, comment='no or yes'),
    sa.Column('youtube_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('how_to_youtube_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('api_docs_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('website_url', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vervotech_hotel_list',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('last_update', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('UpdateDateFormat', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('VervotechId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Latitude', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Longitude', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('AddressLine1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('AddressLine2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CityName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('StateName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('StateCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CountryName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CountryCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PostalCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Rating', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PropertyType', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ChainName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ChainCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('BrandName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CityCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CityLocationId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('MasterCityName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('LocationIds', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Phones', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Emails', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Fax', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Website', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('AirportCodes', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('TrainStations', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderHotelId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderFamily', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GooglePlusCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GooglePlaceId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Tags', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_index', 'vervotech_hotel_list', ['VervotechId'], unique=False)
    op.create_table('akbar_location_master',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('location_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('full_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('score', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('lat', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('long', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('crearted_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vervotech_mapping_2',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('UnicaId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderHotelId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderFamily', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ModifiedOn', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ChannelIds', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderLocationCode', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_unicaid_name', 'vervotech_mapping_2', ['UnicaId'], unique=False)
    op.create_table('users',
    sa.Column('NewField', mysql.VARCHAR(length=255), nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('hotels_info',
    sa.Column('UnicaId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Latitude', mysql.FLOAT(), nullable=True),
    sa.Column('Longitude', mysql.FLOAT(), nullable=True),
    sa.Column('AddressLine1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('AddressLine2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CityName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('StateName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('StateCode', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('CountryName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CountryCode', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('PostalCode', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('Rating', mysql.FLOAT(), nullable=True),
    sa.Column('PropertyType', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ChainName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ChainCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('BrandName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CityCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CityLocationId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('MasterCityName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('LocationIds', mysql.TEXT(), nullable=True),
    sa.Column('Phones', mysql.TEXT(), nullable=True),
    sa.Column('Emails', mysql.TEXT(), nullable=True),
    sa.Column('Fax', mysql.TEXT(), nullable=True),
    sa.Column('Website', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('AirportCodes', mysql.TEXT(), nullable=True),
    sa.Column('TrainStations', mysql.TEXT(), nullable=True),
    sa.Column('ProviderHotelId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderFamily', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GooglePlaceId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Tags', mysql.TEXT(), nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vervotech_hotel_map_new',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('last_update', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('VervotechId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('UpdateDateFormat', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderHotelId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderFamily', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ChannelIds', mysql.JSON(), nullable=True),
    sa.Column('ProviderLocationCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ModifiedOn', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_index', 'vervotech_hotel_map_new', ['VervotechId'], unique=False)
    op.create_index('idx_created_at', 'vervotech_hotel_map_new', ['created_at'], unique=False)
    op.create_table('all_country_name',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('CountryName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CountryCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('RegionName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('RegionCode', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('giata_hotel_mapping',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('giata_old_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('giata_old_id_update_date', mysql.TIMESTAMP(), nullable=True),
    sa.Column('giata_new_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('last_update', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vervotech_hotel_map_update',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('last_update', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('VervotechId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('UpdateDateFormat', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderHotelId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderFamily', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ChannelIds', mysql.JSON(), nullable=True),
    sa.Column('ProviderLocationCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ModifiedOn', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_index', 'vervotech_hotel_map_update', ['VervotechId'], unique=False)
    op.create_table('vervotech_ProviderFamily',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('ProviderFamily', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('iit_supplier_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), server_default=sa.text("'disable'"), nullable=True, comment='disable or active'),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('master_dotw',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('city_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('country_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('country_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('unique_city', 'master_dotw', ['city_code'], unique=True)
    op.create_table('users_for_flask',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'users_for_flask', ['username'], unique=True)
    op.create_table('gitata_provider_family',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('provider_family_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), server_default=sa.text("'active'"), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('country_info',
    sa.Column('Id', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('contentUpdateStatus', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('CityName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CountryName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CountryCode', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('CityCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_country_name', 'country_info', ['CountryName'], unique=False)
    op.create_index('idx_content_update_status', 'country_info', ['contentUpdateStatus'], unique=False)
    op.create_index('idx_city_name', 'country_info', ['CityName'], unique=False)
    op.create_table('hotels_info_with_gidestination_code',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('CityName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CountryName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CountryCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PostalCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GiDestinationId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('StatusDestinationId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CreatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ModifiedOn', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('oryx_destination_id',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('giDestinationId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('destinationId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cityName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('countryName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('stateCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('countryCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('NewField', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mapping_short_info',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Latitude', mysql.FLOAT(), nullable=True),
    sa.Column('Longitude', mysql.FLOAT(), nullable=True),
    sa.Column('AddressLine1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('AddressLine2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CityName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CountryName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Phones', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('PostalCode', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CountryCode', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('idx_name_1', 'mapping_short_info', ['Name'], unique=False)
    op.create_index('idx_name', 'mapping_short_info', ['Name'], unique=False)
    op.create_index('idx_latitude_longitude_1', 'mapping_short_info', ['Latitude', 'Longitude'], unique=False)
    op.create_index('idx_latitude_longitude', 'mapping_short_info', ['Latitude', 'Longitude'], unique=False)
    op.create_index('idx_cityname_1', 'mapping_short_info', ['CityName'], unique=False)
    op.create_index('idx_cityname', 'mapping_short_info', ['CityName'], unique=False)
    op.create_index('idx_address_1', 'mapping_short_info', ['AddressLine1', 'AddressLine2'], unique=False)
    op.create_index('idx_address', 'mapping_short_info', ['AddressLine1', 'AddressLine2'], unique=False)
    op.create_table('vervotech_update_data_info',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('vh_new_total', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('vh_new_newFile', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('vh_new_newFile_updateSuccess', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('vh_new_newFile_updateSkipping', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('vh_new_newFile_lastUpdate_dateTime', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('vh_update_total', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('vh_update_newFile', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('vh_update_newFile_updateSuccess', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('vh_update_newFile_updateSkipping', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('vh_update_newFile_lastUpdate_dateTime', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('global_mapping_total', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('global_mapping_newFile', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('modified_on', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('contentUpdatingStatus', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('total_vervotech_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('total_giata_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('hotelbeds_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('hotelbeds', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('ean_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('ean', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('agoda_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('agoda', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('mgholiday_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('mgholiday', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('restel_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('restel', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('stuba_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('stuba', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('hyperguestdirect_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('hyperguestdirect', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('tbohotel_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('tbohotel', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('goglobal_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('goglobal', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('ratehawkhotel_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('ratehawkhotel', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('adivahahotel_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('adivahahotel', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('grnconnect_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('grnconnect', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('juniper_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('juniper', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('mikihotel_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('mikihotel', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('paximumhotel_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('paximumhotel', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('adonishotel_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('adonishotel', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('w2mhotel_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('w2mhotel', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('oryxhotel_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('oryxhotel', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('dotw_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('dotw', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('hotelston_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('hotelston', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('letsfly_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('letsfly', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('illusionshotel_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('illusionshotel', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('innstanttravel_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('innstanttravel', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('roomerang_total_hotel_ids', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('roomerang', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('lastUpdate', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('vervotech_ids_total', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('giata_ids_total', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('total_mapping_hotel_ids', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('total_country', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('total_city', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('global_hotel_mapping_copy',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('lastUpdate', mysql.TIMESTAMP(), nullable=True),
    sa.Column('mapStatus', mysql.VARCHAR(length=10), server_default=sa.text("'pending'"), nullable=True, comment='pending/updated'),
    sa.Column('ittid', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('VervotechId', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('GiataCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contentUpdateStatus', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Latitude', mysql.FLOAT(), nullable=True),
    sa.Column('Longitude', mysql.FLOAT(), nullable=True),
    sa.Column('AddressLine1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('AddressLine2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CityName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StateName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StateCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CountryName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CountryCode', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('PostalCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Rating', mysql.FLOAT(), nullable=True),
    sa.Column('PropertyType', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ChainName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ChainCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('BrandName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CityCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CityLocationId', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('MasterCityName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('LocationIds', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Phones', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Emails', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Fax', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Website', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('hotelbeds', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ratehawkhotel', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_a', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_b', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_c', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_d', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_e', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('adivahahotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('adivahahotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('juniperhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mikihotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('paximumhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('adonishotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('w2mhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('letsflyhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('illusionshotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('roomerang_a', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('roomerang_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang_e', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('idx_vervotechid_status', 'global_hotel_mapping_copy', ['VervotechId', 'mapStatus'], unique=False)
    op.create_index('idx_tbo', 'global_hotel_mapping_copy', ['tbohotel'], unique=False)
    op.create_index('idx_table_status_goglobal', 'global_hotel_mapping_copy', ['goglobal'], unique=False)
    op.create_index('idx_table_status', 'global_hotel_mapping_copy', ['grnconnect', 'goglobal'], unique=False)
    op.create_index('idx_status', 'global_hotel_mapping_copy', ['GiataCode', 'mapStatus'], unique=False)
    op.create_index('idx_lastUpdate', 'global_hotel_mapping_copy', ['lastUpdate'], unique=False)
    op.create_index('idx_hotelbeds', 'global_hotel_mapping_copy', ['hotelbeds'], unique=False)
    op.create_index('idx_grnconnect', 'global_hotel_mapping_copy', ['grnconnect'], unique=False)
    op.create_index('idx_country_name', 'global_hotel_mapping_copy', ['CountryName'], unique=False)
    op.create_index('idx_content_update_status', 'global_hotel_mapping_copy', ['contentUpdateStatus'], unique=False)
    op.create_index('idx_contentStatus', 'global_hotel_mapping_copy', ['contentUpdateStatus'], unique=False)
    op.create_index('idx_city_name', 'global_hotel_mapping_copy', ['CityName'], unique=False)
    op.create_index('country_code', 'global_hotel_mapping_copy', ['CountryCode'], unique=False)
    op.create_table('vervotech_mapping',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('last_update', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('VervotechId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GiataCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('UpdateDateFormat', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderHotelId', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderFamily', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ModifiedOn', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ChannelIds', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ProviderLocationCode', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hotel_city', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hotel_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hotel_country', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hotel_longitude', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hotel_latitude', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('country_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content_update_status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('vervotech_idx', 'vervotech_mapping', ['VervotechId'], unique=False)
    op.create_index('idx_provider_family_hotel_id', 'vervotech_mapping', ['ProviderFamily', 'ProviderHotelId'], unique=False)
    op.create_index('for_vervotech_id', 'vervotech_mapping', ['VervotechId'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('supplier_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('hotel_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('contact_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('itt_mapping_v01',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('lastUpdate', mysql.TIMESTAMP(), nullable=True),
    sa.Column('mapStatus', mysql.VARCHAR(length=10), server_default=sa.text("'pending'"), nullable=True, comment='pending/updated'),
    sa.Column('ittid', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('VervotechId', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('GiataCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('contentUpdateStatus', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('Name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Latitude', mysql.FLOAT(), nullable=True),
    sa.Column('Longitude', mysql.FLOAT(), nullable=True),
    sa.Column('AddressLine1', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('AddressLine2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CityName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StateName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StateCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CountryName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CountryCode', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('PostalCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Rating', mysql.FLOAT(), nullable=True),
    sa.Column('PropertyType', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ChainName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ChainCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('BrandName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('CityCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('CityLocationId', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('MasterCityName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('LocationIds', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Phones', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Emails', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('Fax', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Website', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('hotelbeds', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelbeds_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ean_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('agoda_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mgholiday_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('restel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('stuba_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hyperguestdirect_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tbohotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('goglobal_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ratehawkhotel', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_a', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_b', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_c', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_d', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ratehawkhotel_e', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('adivahahotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('adivahahotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adivahahotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('grnconnect_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('juniperhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('juniperhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mikihotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('mikihotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('paximumhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('paximumhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('adonishotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('adonishotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('w2mhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('w2mhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('oryxhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('dotw_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hotelston_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('letsflyhotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('letsflyhotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('illusionshotel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('illusionshotel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_a', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('innstanttravel_e', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('roomerang_a', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('roomerang_b', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang_c', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang_d', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('roomerang_e', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('idx_vervotechid_status', 'itt_mapping_v01', ['VervotechId', 'mapStatus'], unique=False)
    op.create_index('idx_tbo', 'itt_mapping_v01', ['tbohotel'], unique=False)
    op.create_index('idx_table_status_goglobal', 'itt_mapping_v01', ['goglobal'], unique=False)
    op.create_index('idx_table_status', 'itt_mapping_v01', ['grnconnect', 'goglobal'], unique=False)
    op.create_index('idx_status', 'itt_mapping_v01', ['GiataCode', 'mapStatus'], unique=False)
    op.create_index('idx_name', 'itt_mapping_v01', ['Name'], unique=False)
    op.create_index('idx_latitude_longitude', 'itt_mapping_v01', ['Latitude', 'Longitude'], unique=False)
    op.create_index('idx_lastUpdate', 'itt_mapping_v01', ['lastUpdate'], unique=False)
    op.create_index('idx_hotelbeds', 'itt_mapping_v01', ['hotelbeds'], unique=False)
    op.create_index('idx_grnconnect', 'itt_mapping_v01', ['grnconnect'], unique=False)
    op.create_index('idx_contentStatus', 'itt_mapping_v01', ['contentUpdateStatus'], unique=False)
    op.create_index('idx_cityname', 'itt_mapping_v01', ['CityName'], unique=False)
    op.create_index('idx_address', 'itt_mapping_v01', ['AddressLine1', 'AddressLine2'], unique=False)
    op.create_index('country_code', 'itt_mapping_v01', ['CountryCode'], unique=False)
    # ### end Alembic commands ###
