name: CI/CD Deploy to Contabo

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Rsync to server
      run: |
        rsync -avz --delete \
          --exclude='.git*' \
          --exclude='__pycache__/' \
          ./ \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/itt-api/HITA-with-FASTapi/

    - name: Deploy on server
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /var/www/itt-api/HITA-with-FASTapi
          pipenv install --deploy --ignore-pipfile
          systemctl restart hita-fastapi
        EOF
